## Multiple Linear Regression

In [3]:
# import libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
# import dataset
dataset = pd.read_csv('50_Startups.csv')

In [6]:
dataset.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [29]:
X = dataset.iloc[:, :-1]
y = dataset.iloc[:, -1]

In [30]:
X.head()

   R&D Spend  Administration  Marketing Spend       State
0  165349.20       136897.80        471784.10    New York
1  162597.70       151377.59        443898.53  California
2  153441.51       101145.55        407934.54     Florida
3  144372.41       118671.85        383199.62    New York
4  142107.34        91391.77        366168.42     Florida

In [31]:
y.head()

0    192261.83
1    191792.06
2    191050.39
3    182901.99
4    166187.94
Name: Profit, dtype: float64

In [32]:
print(dataset.columns.tolist())

['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit']

In [33]:
# Convert the columns into categorical columns

states = pd.get_dummies(X['State'], drop_first=True, dtype=int)

# Drop the State column
X = X.drop('State', axis=1)

states.head()

   Florida  New York
0        0         1
1        0         0
2        1         0
3        0         1
4        1         0

In [37]:
# concat the dummy variables
X= pd.concat([X, states], axis = 1)

In [38]:
X.head()

   R&D Spend  Administration  Marketing Spend  Florida  New York
0  165349.20       136897.80        471784.10        0         1
1  162597.70       151377.59        443898.53        0         0
2  153441.51       101145.55        407934.54        1         0
3  144372.41       118671.85        383199.62        0         1
4  142107.34        91391.77        366168.42        1         0

In [39]:
# Splitting the dataset into the training and test set

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 21)

In [41]:
# Fitting Myltiple Linear Regression to the Training set

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

#Predicting the test set results
y_pred = regressor.predict(X_test)

In [42]:
from sklearn.metrics import r2_score
score = r2_score(y_test, y_pred)

In [43]:
score

0.9633877651304333